site_name: PKU计算机基础能力手册
repo_url: https://github.com/lcpu-club/getting-started-handout-md/
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
#    - navigation.indexes
    - navigation.top
    - navigation.tracking

plugins:
  - search

watch:
  - includes

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  - toc:
      permalink: true

#nav:
#  - HOME:
#      - "index.md"
#      - ABOUT: "./HOME/about.md"
#      - SPONSORSHIP: "./HOME/sponsorship.md"
#  - CS:
#      - "./CS/CS.md"
#  - CODING:
#      - "./CODING/coding.md"
#  - EMBEDDED-SYS:
#      - "./EMBEDDED-SYS/embedded-sys.md"
#  - DSP:
#      - "./DSP/dsp.md"
#  - PERCEPTION:
#      - "./PERCEPTION/perception.md"
#  - ACTUATION:
#      - "./ACTUATION/actuation.md"
#      - ROS: "./ACTUATION/ROS/ros.md"
#  - IOT:
#      - "./IOT/iot.md"
#  - CLOUD:
#      - "./CLOUD/cloud.md"
#      - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"
#      - HANDS-ON:
#          - Have A Server: "./CLOUD/HANDS-ON/001-HAVE-A-SERVER/have-a-server.md"
#          - Server Configuration: "./CLOUD/HANDS-ON/002-SERVER-CONFIG/server-config.md"
#          - Get A Domain Name: "./CLOUD/HANDS-ON/003-DOMAIN-NAME/domain-name.md"
#  - :simple-git:GIT:
#      - icon: simple-git
#      - "./git/index.md"
#  - RESEARCH:
#      - "./RESEARCH/research.md"
#  - PROJECT:
#      - "./PROJECT/project.md"
#      - TECH-BLOG: "./PROJECT/TECH-BLOG/mkdocs_and_material.md"

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js